version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_DB: explorer_dev
      POSTGRES_PASSWORD: ""
    ports:
      - 5432:5432
    volumes:
      - blockscout_pgdata:/var/lib/postgresql/data

volumes:
  blockscout_pgdata:
    external: true
